clear
clc
close all
tic
gm = multisphere([1,2,4,6],"Void",[true,false,false,false]);
pdegplot(gm,FaceAlpha=0.25,CellLabel="on")
pdegplot(gm,FaceAlpha=0.25,FaceLabel="on")
model = femodel(AnalysisType="thermalTransient", ...
                Geometry=gm);
model = generateMesh(model,Hmax=1);
model.MaterialProperties(1) = ...
    materialProperties(ThermalConductivity=1, ...
                       MassDensity=1, ...
                       SpecificHeat=1);
model.MaterialProperties(2) = ...
    materialProperties(ThermalConductivity=2, ...
                       MassDensity=1, ...
                       SpecificHeat=0.5);
model.MaterialProperties(3) = ...
    materialProperties(ThermalConductivity=4, ...
                       MassDensity=1, ...
                       SpecificHeat=4/9);
model.FaceBC(1) = faceBC(Temperature=0);
model.FaceLoad(4) = faceLoad(Heat=@externalHeatFlux);
model.CellIC = cellIC(Temperature=0);
tlist = [0,2,5:5:50];
R = solve(model,tlist);
toc